### ISSUE TITLE
Character has no stroke count information

### ISSUE THREAD

**Issue by ruddfawcett** [cburgmer/cjklib#10]
Hi @cburgmer, thanks so much for this library. After a bit of fiddling, I was able to get everything going! Everything I've tried so far works: translation, pinyin, etc. I can't, however, seem to figure out `getStrokeCount()`:

```python
from cjklib.characterlookup import CharacterLookup
cjk = CharacterLookup('C')
print(cjk.getStrokeCount(u'说'))
```

When I run the above, I get the following:
> Traceback (most recent call last):
> File "/Users/user/Documents/GitHub/chinese/hanzi.csv/generate.py", line 7, in <module> print(cjk.getStrokeCount(u'说'))
> File "/Users/user/Documents/GitHub/chinese/hanzi.csv/cjklib/characterlookup.py", line 644, in getStrokeCount
> "Character has no stroke count information")
cjklib.exception.NoInformationError: Character has no stroke count information

I've tried rebuilding the databases, reinstalling, etc. but no luck. I was wondering if you had any suggestions?

**Comment by ruddfawcett** [comment]
Nevermind! Just found this which I can use instead: http://hanzidb.org/character-list/by-frequency. Thanks!

**Comment by cburgmer** [comment]
Happy you found a solution. I haven't looked in the cjklib in a while, some things might need fixing up after this long time.
