### ISSUE TITLE
cjklib.org is down

### ISSUE THREAD

**Issue by ghost** [cburgmer/cjklib#14]

**Comment by cburgmer** [comment]
Thanks. I dropped the ball on the domain renewal. I believe I cannot get it back now.
The content should still exist though, let me dig up the link.

**Comment by cburgmer** [comment]
Please find the API documentation under http://cburgmer.nfshost.com/cjklib/0.3/index.html.

Let me know if you are missing anything else.

**Comment by ghost** [comment]
Awesome! Thanks for digging that up for me.
